### ISSUE TITLE
Tab causes course description to scroll

### ISSUE THREAD

**Issue by noisecapella** [mitodl/ocw-hugo-themes#81] opened 2021-06-02 12:02 UTC
### Steps to Reproduce

On `8-01sc-classical-mechanics-fall-2016` go to the course home page, then press tab. The tab focuses on the "Get Started" button and scrolls the div in the collapsed view (see screenshot). Instead a tab should probably skip anything inside the course description and focus on the Read More link instead.

### Screenshot or Screencast

![Screenshot from 2021-06-02 07-58-39](https://user-images.githubusercontent.com/863262/120476370-83396280-c378-11eb-846c-3345755a5415.png)

**Comment by MAbdurrehman12** [comment] 2022-01-25 08:05
@pdpinch The design has been changed, do we still need this ticket? 
I also tried to reproduce the issue but couldn't reproduce it and I'm also not sure which `tab` is being referred here.

**Comment by pdpinch** [comment] 2022-01-25 18:40
I'm closing this. We will have another accessibility review which will catch this, if it is still an issue.

**Closed by pdpinch** 2022-01-25 18:40 UTC
Labels: bug
